### ISSUE TITLE
Dataset specifics

### ISSUE THREAD

**Issue by DavidBoja** [wangsen1312/unsupervised3dhuman#8]
Hi, 

could you specify which subjects and frames did you use to evaluate the methods on the CAPE and CMU datasets (Table 1 and 2 from the paper) ?

Thank you in advance.

**Comment by wangsen1312** [comment]
Sorry for the so late response.  I don't know why some github emails went to the junk mail.
For CAPE dataset,  we have use the same settings as PTF [1].  We subsampled the sequences by a factor of 5. 
For CMU dataset, we have choose several sequences provided with 3D GT.   Since the sequences are too long, we subsampled the sequences by a factor of 20.

[1] Locally aware piecewise transformation fields for 3d human mesh registration. CVPR 2021

I will give you more details when I can check the lists off the work.
